from enum import StrEnum

class JobStatus(StrEnum):
    RECEIVED='RECEIVED'; QUEUED='QUEUED'; ACTIVE='ACTIVE'; WAIT_HITL='WAIT_HITL'; READY='READY'; DONE='DONE'; RETRY_WAIT='RETRY_WAIT'; FAILED='FAILED'; CLOSED='CLOSED'

class ActionMode(StrEnum):
    OFF='OFF'; VIEW_ONLY='VIEW_ONLY'; PROPOSE='PROPOSE'; APPROVE_TO_ACT='APPROVE_TO_ACT'

class PromiseStatus(StrEnum):
    OPEN='OPEN'; FULFILLED='FULFILLED'; WAIT_HITL='WAIT_HITL'; FAILED='FAILED'; CANCELLED='CANCELLED'

class FeedbackScope(StrEnum):
    THIS_JOB='THIS_JOB'; THIS_JOB_TYPE='THIS_JOB_TYPE'; THIS_USER='THIS_USER'; DEPARTMENT_CANDIDATE='DEPARTMENT_CANDIDATE'
